name: flutter_down_menu
description: Customize the drop-down menu, quickly realize the head drop-down menu,
  and support the rapid realization of single selection, multiple selection list, secondary list, single selection, multiple selection and other functions.
  You can also customize the header and selection list styles.\n
  自定义下拉菜单,快速实现头部下拉菜单，支持单选、多选列表，二级列表单选、多选等功能快速实现。也可以自定义头部和选择列表样式。
version: 0.0.3
homepage: https://github.com/lixp185/flutter_down_menu

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


