name: flutter_down_menu
description: Flutter自定义下拉菜单
version: 0.0.1
homepage: https://github.com/lixp185/flutter_down_menu

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


